export const SUPPORTED_LANGUAGES = [
  { id: "javascript", name: "JavaScript", extension: ".js" },
  { id: "typescript", name: "TypeScript", extension: ".ts" },
  { id: "python", name: "Python", extension: ".py" },
  { id: "java", name: "Java", extension: ".java" },
  { id: "cpp", name: "C++", extension: ".cpp" },
  { id: "c", name: "C", extension: ".c" },
  { id: "csharp", name: "C#", extension: ".cs" },
  { id: "go", name: "Go", extension: ".go" },
  { id: "rust", name: "Rust", extension: ".rs" },
  { id: "php", name: "PHP", extension: ".php" },
  { id: "ruby", name: "Ruby", extension: ".rb" },
  { id: "swift", name: "Swift", extension: ".swift" },
  { id: "kotlin", name: "Kotlin", extension: ".kt" },
  { id: "dart", name: "Dart", extension: ".dart" },
  { id: "html", name: "HTML", extension: ".html" },
  { id: "css", name: "CSS", extension: ".css" },
  { id: "json", name: "JSON", extension: ".json" },
  { id: "yaml", name: "YAML", extension: ".yaml" },
  { id: "markdown", name: "Markdown", extension: ".md" },
  { id: "sql", name: "SQL", extension: ".sql" },
  { id: "shell", name: "Shell", extension: ".sh" },
  { id: "dockerfile", name: "Dockerfile", extension: "Dockerfile" },
] as const;
